#https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}--postgres-cluster
  namespace: default
spec:
  teamId: "mda"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    mda:  # database owner
    - superuser
    - createdb
  databases:
    mda: mda  # dbname: owner
  postgresql:
    version: "14"
---
