apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prediction
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-prediction
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-prediction
    spec:
      containers:
      - image: {{ .Values.images.prediction }}
        name: prediction
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: 1100Mi
          requests:
            memory: 1100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prediction
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    name: {{ .Release.Name }}-prediction
